# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/traffic_violation_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=create

# JWT
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration=86400000

# MQTT
app.mqtt.broker-url=tcp://localhost:1883
app.mqtt.username=
app.mqtt.password=
app.mqtt.client-id=traffic-system-server
app.mqtt.topic.cameras=cameras/#

#Mail
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

app.pdf.output-dir=./generated-reports

spring.profiles.active=dev