package com.academy.trafficviolationsystem.payment;

import com.academy.trafficviolationsystem.core.entities.UUIDBaseEntity;
import com.academy.trafficviolationsystem.fine.FineEntity;
import com.academy.trafficviolationsystem.user.UserEntity;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * One payment transaction attempt against a fine.
 *
 * Extends UUIDBaseEntity — inherits id (UUID), created, updated,
 * createdBy, updatedBy, deletedAt (soft-delete).
 *
 * Multiple rows per fine are expected and valid:
 *   Row 1 — CREDIT_CARD FAILED (wrong car d number)
 *   Row 2 — CREDIT_CARD SUCCESS (correct card on retry)
 * FineService.markPaid() is called only when a row transitions to SUCCESS.
 *
 * Idempotency:
 *   transactionId is generated by PaymentService before calling the gateway
 *   simulator. PaymentRepository.existsByTransactionId() guards against
 *   duplicate submissions from a double-click or network retry.
 *
 * Receipt PDF:
 *   receiptPdfPath is null until PaymentConfirmationPdfService finishes the
 *   async generation. The DTO exposes a computed receiptReady flag so the
 *   frontend can poll or check before offering a download link.
 */
@Getter
@Setter
@Entity
@Table(
    name = "payments",
        uniqueConstraints = {
                @UniqueConstraint(name = "uk_payment_txn_id", columnNames = "transaction_id"),
                @UniqueConstraint(name = "uk_payment_idempotency_key", columnNames = "idempotency_key")
        },
    indexes = {
        @Index(name = "idx_payment_fine",   columnList = "fine_id"),
        @Index(name = "idx_payment_status", columnList = "status"),
        @Index(name = "idx_payment_tid",    columnList = "transaction_id"),
        @Index(name = "idx_payment_paidby", columnList = "paid_by_id")
    }
)
public class PaymentEntity extends UUIDBaseEntity {

    // ── transaction reference ─────────────────────────────────────────────

    /**
     * Simulated gateway transaction reference.
     * Format: TXN-{YYYYMMDD}-{6-digit-seq}, e.g. TXN-20250601-000042.
     * Generated by PaymentService before the gateway call so it can be
     * used as an idempotency key regardless of gateway outcome.
     */
    @Column(name = "transaction_id", nullable = false, length = 40)
    private String transactionId;

    @Column(name = "idempotency_key", nullable = false, length = 64)
    private String idempotencyKey;

    // ── amounts ───────────────────────────────────────────────────────────

    /**
     * Amount tendered in this transaction.
     * Copied from fine.totalDue at the moment of payment — stored here so
     * the receipt always reflects the amount actually charged even if the
     * fine is later modified.
     */
    @Column(name = "amount", nullable = false, precision = 10, scale = 2)
    private BigDecimal amount;

    @Column(name = "currency", nullable = false, length = 3)
    private String currency = "BAM";

    // ── payment details ───────────────────────────────────────────────────

    @Enumerated(EnumType.STRING)
    @Column(name = "method", nullable = false, length = 20)
    private PaymentMethod method;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 20)
    private PaymentStatus status;

    /** Populated when status transitions to SUCCESS. */
    @Column(name = "paid_at")
    private LocalDateTime paidAt;

    /**
     * Raw JSON response string from PaymentGatewaySimulator.
     * Stored for audit and debugging — never parsed after storage.
     */
    @Column(name = "gateway_response", columnDefinition = "TEXT")
    private String gatewayResponse;

    /**
     * Path to generated receipt PDF.
     * Null until PaymentConfirmationPdfService completes async generation.
     */
    @Column(name = "receipt_pdf_path")
    private String receiptPdfPath;

    /** Cashier notes, failure reason, or reference number for bank transfers. */
    @Column(name = "notes")
    private String notes;

    // ── relationships ─────────────────────────────────────────────────────

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
        name = "fine_id",
        nullable = false,
        foreignKey = @ForeignKey(name = "fk_payment_fine")
    )
    private FineEntity fine;

    /**
     * The user who initiated the payment — citizen via portal, or officer
     * accepting cash/card at a payment centre.
     * Null if initiated by an anonymous public-facing process (not used in this system).
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
        name = "paid_by_id",
        foreignKey = @ForeignKey(name = "fk_payment_user")
    )
    private UserEntity paidBy;
}
